import {
  Brain,
  Wrench,
  Cpu,
  Sparkles,
  Send,
  ArrowRight,
  Eye,
  PenLine,
  MessageSquare,
  Target,
  AlertTriangle,
} from "lucide-react";
import type { ExecutionStep, StepType } from "./types";

export const stepConfig: Record<StepType, { icon: React.ElementType; badge: string }> = {
  task_input: { icon: Target, badge: "INPUT" },
  reasoning: { icon: Brain, badge: "REASON" },
  model_call: { icon: Cpu, badge: "LLM" },
  model_response: { icon: MessageSquare, badge: "RESPONSE" },
  tool_call: { icon: Wrench, badge: "TOOL" },
  tool_response: { icon: Send, badge: "RESULT" },
  memory_read: { icon: Eye, badge: "READ" },
  memory_write: { icon: PenLine, badge: "WRITE" },
  decision: { icon: Sparkles, badge: "DECIDE" },
  output: { icon: ArrowRight, badge: "OUTPUT" },
  error: { icon: AlertTriangle, badge: "ERROR" },
};

export const mockExecution: ExecutionStep[] = [
  {
    id: "s1",
    type: "task_input",
    label: "Task received",
    status: "success",
    loop: 1,
    timestamp: "00:00.000",
    processingMs: 300,
    content:
      'Route and resolve: "I was charged twice for my subscription last month. Account ACC-4829."',
  },
  {
    id: "s2",
    type: "reasoning",
    label: "Planning approach",
    status: "success",
    loop: 1,
    timestamp: "00:00.012",
    duration: "45ms",
    processingMs: 800,
    content:
      "User reports duplicate billing charge. Need to:\n1. Verify account exists\n2. Pull recent billing history\n3. Confirm duplicate\n4. Route to billing team with refund recommendation",
  },
  {
    id: "s3",
    type: "model_call",
    label: "gpt-4.1 → identify intent",
    status: "success",
    loop: 1,
    timestamp: "00:00.057",
    duration: "620ms",
    tokens: 284,
    cost: "$0.004",
    processingMs: 1200,
    content:
      "System: You are a customer support routing agent...\nUser: I was charged twice for my subscription last month...",
    meta: { model: "gpt-4.1", temperature: "0.3", max_tokens: "1024" },
  },
  {
    id: "s4",
    type: "model_response",
    label: "Intent classified → billing_dispute",
    status: "success",
    loop: 1,
    timestamp: "00:00.677",
    duration: "620ms",
    tokens: 156,
    processingMs: 500,
    content:
      "Classification: billing_dispute (confidence: 0.97)\nRequired tools: lookup_billing, verify_account\nEscalation: not yet — attempting resolution first",
  },
  {
    id: "s5",
    type: "memory_read",
    label: "Checking customer history",
    status: "success",
    loop: 1,
    timestamp: "00:00.680",
    duration: "18ms",
    processingMs: 400,
    content:
      'Key: customer:ACC-4829\nResult: { prior_tickets: 2, sentiment: "neutral", tier: "pro", ltv: "$1,200" }',
    meta: { source: "Local Store", keys_accessed: "1" },
  },
  {
    id: "s6",
    type: "tool_call",
    label: "lookup_billing(ACC-4829)",
    status: "success",
    loop: 1,
    timestamp: "00:00.698",
    duration: "289ms",
    processingMs: 900,
    content:
      '{\n  "function": "lookup_billing",\n  "arguments": {\n    "account_id": "ACC-4829",\n    "date_range": "last_30_days"\n  }\n}',
  },
  {
    id: "s7",
    type: "tool_response",
    label: "lookup_billing → duplicate found",
    status: "success",
    loop: 1,
    timestamp: "00:00.987",
    duration: "289ms",
    processingMs: 400,
    content:
      '{\n  "charges": [\n    { "date": "2024-01-15", "amount": "$29.99", "desc": "Pro Subscription" },\n    { "date": "2024-01-15", "amount": "$29.99", "desc": "Pro Subscription (duplicate)" }\n  ],\n  "status": "duplicate_detected"\n}',
  },
  {
    id: "s8",
    type: "decision",
    label: "Refund recommended → escalate",
    status: "success",
    loop: 2,
    timestamp: "00:01.002",
    duration: "12ms",
    processingMs: 600,
    content:
      "Duplicate charge confirmed ($29.99). Customer is Pro tier with positive history.\nDecision: Escalate to billing with immediate refund recommendation.\nConfidence: 0.99",
  },
  {
    id: "s9",
    type: "memory_write",
    label: "Updating customer context",
    status: "success",
    loop: 2,
    timestamp: "00:01.014",
    duration: "8ms",
    processingMs: 350,
    content:
      'Key: customer:ACC-4829\nUpdated: { last_issue: "billing_dispute", resolution: "refund_pending", updated_at: "2024-01-16T..." }',
    meta: { source: "Local Store", keys_written: "1" },
  },
  {
    id: "s10",
    type: "model_call",
    label: "gpt-4.1 → compose response",
    status: "success",
    loop: 2,
    timestamp: "00:01.022",
    duration: "398ms",
    tokens: 580,
    cost: "$0.008",
    processingMs: 1100,
    content:
      "System: Compose a customer-facing response for billing dispute resolution...\nContext: duplicate charge confirmed, refund recommended...",
    meta: { model: "gpt-4.1", temperature: "0.3" },
  },
  {
    id: "s11",
    type: "output",
    label: "Final response delivered",
    status: "success",
    loop: 2,
    timestamp: "00:01.420",
    duration: "398ms",
    tokens: 262,
    cost: "$0.003",
    processingMs: 500,
    content:
      "I found the issue — you were charged twice on Jan 15th for your Pro Subscription ($29.99 each).\n\nI've escalated this to our billing team with a refund recommendation for the duplicate charge.\n\n**Reference:** REF-8842\n**Expected resolution:** 2–3 business days.",
  },
];

export const filterOptions: { value: StepType | "all"; label: string }[] = [
  { value: "all", label: "All steps" },
  { value: "reasoning", label: "Reasoning" },
  { value: "model_call", label: "LLM" },
  { value: "tool_call", label: "Tools" },
  { value: "memory_read", label: "Memory" },
  { value: "decision", label: "Decisions" },
];
